### ISSUE TITLE
Table userdb cannot be created after database initialization

### ISSUE THREAD

**Issue by skleeab** [BlackDavy/COMP4111_Phase2#1]
### Description
Table ```userdb``` cannot be created after database initialization.

### How to reproduce
1. Run the SQL file called initialDB.sql.

### Expected results
Tables ```userdb``` and ```bookdb``` are created.

### What actually happens
```userdb``` cannot be created and error message was shown as below:
```
ERROR 1064 (42000) at line 16: You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for the right syntax to use near ')
charset=utf8' at line 6
```

**Comment by BlackDavy** [comment]
Thx for reminding.
