### ISSUE TITLE
[Book LookUp] sortby not working

### ISSUE THREAD

**Issue by oscarngncc** [BlackDavy/COMP4111_Phase2#7]
*** Issue
sortby not working accordingly. It just returns result as if it's unsorted

### Reproduce:
1. Login accordingly
2. Assumed that the database has a variety of books
3. Lookup book with filter based on year/author and sortby=desc or asc
4. Observe the result

### Output
Expected: result correctly sorted
Actual: result being unsorted

NOTE: the response is actually still plain text described in #6 , I just pretty print it in JSON format inside the API testing client
![image](https://user-images.githubusercontent.com/29769020/83478293-16229100-a4c8-11ea-8d24-9b9fc5ee2bb2.png)

![image](https://user-images.githubusercontent.com/29769020/83478316-220e5300-a4c8-11ea-809c-7d6f6561ea25.png)

**Comment by BlackDavy** [comment]
According to specification, _the sortby parameter specifies the criterion of ordering the returned records and its value can be id, title or author_ , no requirement on year.
